spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms3db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      org:
        hibernate:
          flushMode: COMMIT
  flyway:
    enabled: true

server:
  servlet:
    context-path: /contact
