CREATE TABLE IF NOT EXISTS contact (
    id SERIAL primary key,
    created timestamp,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    date_of_birth VARCHAR(255),
    gender VARCHAR(255),
    title VARCHAR(255),
    type VARCHAR(255),
    number VARCHAR(255),
    street VARCHAR(255),
    unit VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    zip_code VARCHAR(255),
);